prism-php/prism

README.md

Hey TJ,
Great work on the package!
I'm building AI apps with Laravel, and I can already see how useful this will be.
This is my first pull request, which suggests an update to the README.
I recommend using the default namespace in the examples to reduce unnecessary complexity.
Thanks again for all your effort—really excited to see where this goes!

docs: default Laravel namespace path

---

README.md

Currently, the "Open Source Community" link under the Author section in the readme file directs to Vercel's AI repository instead of the repository's "Contributors" page. I have prepared the PR for your review.

Fix: Readme file contributor link

---

composer.json
rector.php
src/Concerns/HasClientOptions.php
src/Concerns/HasModel.php
src/Concerns/HasProvider.php
src/Contracts/Provider.php
src/Generators/TextGenerator.php
src/PrismManager.php
src/Providers/Anthropic/Anthropic.php
src/Providers/Anthropic/Client.php
src/Providers/Mistral/Client.php
src/Providers/Mistral/Mistral.php
src/Providers/Ollama/Client.php
src/Providers/Ollama/Ollama.php
src/Providers/OpenAI/Client.php
src/Providers/OpenAI/OpenAI.php
src/Rectors/ReorderMethodsRector.php
tests/Generators/TextGeneratorTest.php
tests/Providers/OpenAITextTest.php
tests/TestDoubles/TestProvider.php

Allow for client options to be passed to the provider.
```php
Prism::text()
->using(Provider::Ollama, 'qwen2.5')
->withClientOptions(['timeout' => '30'])
->generate()
```
With client options will accept any of [Guzzle's request options](https://docs.guzzlephp.org/en/stable/request-options.html).

Allow for client options + refactors

---

src/Providers/Anthropic/MessageMap.php
tests/Providers/Anthropic/AnthropicTextTest.php
tests/Providers/Anthropic/MessageMapTest.php
tests/Providers/Anthropic/ToolTest.php

This PR updates the Anthropic provider to handle `SystemMessages` as a user message rather than throwing.

Handle system messages as user for Anthropic

---

docs/core-concepts/text-generation.md
src/Concerns/BuildsTextRequests.php
src/Providers/Anthropic/Anthropic.php
src/Providers/Groq/Groq.php
src/Providers/Mistral/Mistral.php
src/Providers/Ollama/Ollama.php
src/Providers/OpenAI/OpenAI.php
src/Providers/XAI/XAI.php
src/Text/Request.php
tests/Generators/TextGeneratorTest.php
tests/TestDoubles/TestProvider.php

Allow for client retry to be passed to Laravel HTTP wrapper (https://laravel.com/docs/11.x/http-client#retries).
```php
Prism::text()
->using(Provider::Anthropic, 'claude-3-5-sonnet-20240620')
->withClientRetry(3, 100)
->generate()
```
or
```php
Prism::text()
->using(Provider::Anthropic, 'claude-3-5-sonnet-20240620')
->withClientRetry(3, 100, function (Exception $exception, PendingRequest $request) {
// 529 - overloaded_error: Anthropic's API is temporarily overloaded.
// https://docs.anthropic.com/en/api/errors
return $exception->getCode() === 529;
})
->generate()
```

Proxy retry call to Laravel HTTP client

---

docs/core-concepts/structured-output.md
docs/core-concepts/testing.md
docs/core-concepts/text-generation.md
src/Concerns/BuildsTextRequests.php
src/Prism.php
src/PrismManager.php
src/Structured/Generator.php
src/Testing/PrismFake.php
src/Text/Generator.php
tests/Generators/StructuredGeneratorTest.php
tests/Generators/TextGeneratorTest.php
tests/PrismManagerTest.php
tests/Testing/PrismFakeTest.php

Closes #92 
This PR adds support for overriding / updating the provider configuration on the fly. This is great for multi-tenant situations where users may bring their own API keys.
```php
Prism::text()
->usingProviderConfig(['api_key' => '1234']);
Prism::structured()
->usingProviderConfig(['api_key' => '1234']);
```
These values are merged with the original provider config values so partial overrides are possible.

Dynamic provider config

---

docs/core-concepts/structured-output.md
src/Structured/Response.php
src/Structured/ResponseBuilder.php
tests/Generators/StructuredGeneratorTest.php
tests/Providers/Anthropic/StructuredTest.php
tests/Providers/Ollama/StructuredTest.php
tests/Providers/OpenAI/StructuredTest.php

Got some feedback that the response for structured output having the attribute `->object` is kind of misleading. This PR refactors the structured response to use `->structured` instead.
- `object` is now `structured` in structured output response

Rename object to structured for structured response

---

src/Exceptions/PrismException.php

Hi! Noticed a typo while using Prism on a project of my own using the structured output for some document analysis via Llama/OpenRouter. Wanted to get my feet wet as I love this project and the direction it's going, definitely want to contribute more!

Fix typo for structured response exceptions

---

docs/core-concepts/tools-function-calling.md

Fix incorrect method name from ->toolChoice() to ->withToolChoice() in the documentation

fix: correct method name for tool choice in documentation

---

docs/components/ProviderSupport.vue
docs/providers/anthropic.md
src/Providers/Anthropic/Maps/MessageMap.php
src/ValueObjects/Messages/Support/Document.php
tests/Fixtures/test-text.md
tests/Fixtures/test-text.txt
tests/Providers/Anthropic/MessageMapTest.php

The recent Anthropic citations release brings with it support for text documents (independent of whether you are using citations or not).
This PR adds support for text documents, ahead of a larger PR to support citations.

Text document handling [Anthropic only]

---

src/Concerns/ConfiguresProviders.php
tests/Text/PendingRequestTest.php

A micro PR to add getters to `ConfiguresProviders` - for convenience where they have been dynamically set and you need to apply some logic based on the `PendingRequest`.

feat: Add getters to ConfiguresProviders

---

src/Structured/Generator.php
tests/Structured/GeneratorTest.php
tests/Text/GeneratorTest.php

This one is on me - in #146 I re-instated the system and user message to the first step, but accidently knocked off the assistant message. Oh the irony!
Have fixed + expanded the test for text and structured to cover this.

fix: reinstate assistant message to steps

---

src/Concerns/ConfiguresModels.php
src/Providers/DeepSeek/Handlers/Structured.php
src/Providers/DeepSeek/Handlers/Text.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php

This PR defaults `maxTokens` to 2048 to keep the same behaviour as today, whilst respecting developer requests to set value to `null`.

Support null value maxTokens

---

src/Concerns/HasProviderMeta.php
src/Structured/Request.php
src/Text/Request.php
tests/Structured/PendingRequestTest.php
tests/Text/PendingRequestTest.php

A nice easy and self-explanatory one.
I ran into this building the Bedrock installable provider, as currently hooking in as a customer provider which has no enum case.

refacor: provider meta as string keys

---

src/Providers/OpenAI/Support/StructuredModeResolver.php
tests/Providers/OpenAI/StructuredTest.php

This PR updates the current OpenAI models that don't support Structured Outputs.
The `o1` model that now shorthands to `o1-2024-12-17` introduced support for structured responses, as per this [blog post](https://openai.com/index/o1-and-new-tools-for-developers/) and testing.

feat(openai): update structured output models

---

src/Providers/OpenAI/Maps/ToolMap.php

OpenAI supports functions that don't take any parameters.
If you pass an empty array of parameters an error is returned:
```Sending to model (model-name) failed: OpenAI Error:  [invalid_request_error] Invalid schema for function 'tool_name': [] is not of type 'object'.```
You instead don't send `parameters` when defining a function without arguments.

fix(openai): function definitions without parameters

---

src/Concerns/CallsTools.php
src/Tool.php
tests/ToolTest.php

While debugging failed tool calls, I was finding it hard to understand quickly why `Calling tool failed` was being thrown.
It was due to the model inventing named parameters to send as an argument to the function.
This change helps expose this problem quicker by:
- Catching PHPs `Unknown named parameter` errors as an additional `invalidParameterInTool` error.
- Throwing a previous `PrismException` rather than `toolCallFailed` when the tool fails.

fix(tools): catch unknown named parameter errors

---

docs/core-concepts/testing.md

The correct namespace for ProviderResponse is `EchoLabs\Prism\ValueObjects\ProviderResponse`.

docs: correct namespace for ProviderResponse

---

src/Providers/Anthropic/Anthropic.php
src/Providers/Anthropic/Handlers/AnthropicHandlerAbstract.php
src/Providers/Anthropic/Handlers/Structured.php
src/Providers/Anthropic/Handlers/Text.php

Refactor Anthropic for #185.
Note, I have allowed FinishReason::Length as a valid stop reason. I am not sure what the behaviour is in practice with Ollama and OpenAI (i.e. does it still provide a valid response) - but we may wish to consider adding to those also.

refactor(anthropic): return final Response

---

src/Providers/Anthropic/Handlers/Structured.php

Not really a bug as such, but we've notice Sonnet 3.7 is more prone to including content outside of the JSON, particularly backticks or code blocks.
We'll continue to monitor - if this doesn't do it we could resort to string manipulation for common fail cases.

bug(anthropic): improve structured shim

---

docs/core-concepts/testing.md

Post refactor I've found tests a little more clumsy to write if you app relies on e.g. inspecting the steps - and that its easier to just do this with the ResponseBuilder which saves some repetition. 
This PR adds an example of using `ResponseBuilder` in tests.

docs(testing): add ResponseBuilder example

---

config/prism.php
docs/providers/anthropic.md
src/Contracts/PrismRequest.php
src/PrismManager.php
src/Providers/Anthropic/Handlers/AnthropicHandlerAbstract.php
src/Providers/Anthropic/Handlers/Structured.php
src/Providers/Anthropic/Handlers/Text.php
src/Providers/Anthropic/Maps/MessageMap.php
tests/Fixtures/anthropic/structured-with-extending-thinking-1.json
tests/Fixtures/anthropic/text-with-extending-thinking-1.json
tests/Fixtures/anthropic/text-with-extending-thinking-and-tool-calls-1.json
tests/Fixtures/anthropic/text-with-extending-thinking-and-tool-calls-2.json
tests/Fixtures/anthropic/text-with-extending-thinking-and-tool-calls-3.json
tests/Providers/Anthropic/AnthropicTextTest.php
tests/Providers/Anthropic/MessageMapTest.php
tests/Providers/Anthropic/StructuredTest.php

Implements the new extended thinking mode for Anthropic, which only works with the new Claude Sonnet 3.7.
There are a lot of interplays with other Anthropic functionality like caching, tool use, etc. I decided to not try and address that in Prism as it'll be subject to change and makes the provider more brittle. Ultimately the developer will get exceptions anyway.
There's some config points to note which I will add to the docs:
- Added a config for default thinking budget, which will default to 1024 (the minimum) if not set in config or in provider meta.
- Added a config for the anthropic-beta header, which is currently required for extended output.

feat(anthropic): extended thinking

---

docs/components/ProviderSupport.vue
docs/providers/gemini.md
src/Providers/Gemini/Gemini.php
src/Providers/Gemini/Handlers/Structured.php
src/Providers/Gemini/Maps/SchemaMap.php

Created this PR before realising [this one](https://github.com/echolabsdev/prism/pull/173) existed.
The main difference is this PR updates the structured output to match the schema format Google defines. It then passes this directly using `response_schema` rather than appending a message.
To me this seems the preferred way of doing it:
- The schema matching the defined format is going to help the model know how to use your schema.
- Passing the schema via `response_schema` means you get validation (and relevant errors) on your schema

feat(gemini): support structured outputs

---

src/Providers/Gemini/Maps/MessageMap.php
src/Providers/Gemini/Maps/ToolMap.php
src/Tool.php

In the same vein as https://github.com/echolabsdev/prism/pull/165 this PR allows calling tools with Gemini that don't require parameters

fix(gemini): support tool calling without params

---

src/Providers/OpenAI/Handlers/Stream.php

For easier debugging of streamed responses, allow the Client to throw exceptions

feat(openai): Stream handler client throws

---

src/Providers/OpenAI/Handlers/Text.php

Noticed that OpenAI was throwing the wrong exception message. I do see that the exception handling will be refactored via https://github.com/echolabsdev/prism/issues/205 but wanted to throw in now anyway.
none
Love the project, appreciate your work!

fix(openai): use open ai in exception message

---

src/Providers/Anthropic/Maps/ToolChoiceMap.php

For Anthropic all tool choices (not just named tools) must be returned in an object with a `type` key (https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview#example-simple-tool-definition).
This PR fixes that, and also adds a mapping for `ToolChoice::None`

fix(anthropic): tool choice must be object

---

src/Providers/XAI/Concerns/ValidatesResponses.php
src/Providers/XAI/Handlers/Text.php
tests/Providers/XAI/XAITextTest.php

Implements rate limit exception for XAI No rate limit details or meta as XAI do not return headers.
Note: I have not updated the docs page as I am doing a couple of these today and don't want to cause a conflict. Will circle back after PRs are merged to update.

feat(xai): rate limit exception

---

src/Providers/VoyageAI/Embeddings.php
tests/Providers/VoyageAI/EmbeddingsTest.php

Implements rate limit exception for VoyageAI. No rate limit details or meta as Voyage do not return headers.
Note: I have not updated the docs page as I am doing a couple of these today and don't want to cause a conflict. Will circle back after PRs are merged to update.

feat(voyageai): rate limit exception

---

.gitignore
src/Providers/OpenAI/Concerns/ValidatesResponse.php
src/Providers/OpenAI/Concerns/ValidatesResponses.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php
tests/Providers/OpenAI/OpenAIExceptionsTest.php
tests/Providers/OpenAI/StructuredTest.php
tests/Providers/OpenAI/TextTest.php

Implements the rate limit exception and meta for OpenAI text and structured (cc #221).
Will look into streaming and embeddings separately.
Note: I have not updated the docs page as I am doing a couple of these today and don't want to cause a conflict. Will circle back after PRs are merged to update.

feat(openai): rate limit exception and meta

---

.gitignore
src/Providers/Gemini/Concerns/ValidatesResponse.php
src/Providers/Gemini/Handlers/Embeddings.php
src/Providers/Gemini/Handlers/Structured.php
src/Providers/Gemini/Handlers/Text.php
tests/Providers/Gemini/GeminiExceptionsTest.php

Implements the rate limit exception for Gemini.
Note, Gemini does not seem to return rate limit headers on responses, so its not possible to implement meta.
They also don't document if/how they communicate which rate limits you have hit... So the rate limit exception is bare for now (no rate limit details).
Note: I have not updated the docs page as I am doing a couple of these today and don't want to cause a conflict. Will circle back after PRs are merged to update. Will note the limitations above in the docs when I do.
Note: will conflict with #219. I will rebase and rectify whichever gets merged second.

feat(gemini): rate limit exception

---

src/Providers/OpenAI/Concerns/ProcessesRateLimits.php
tests/Fixtures/FixtureResponse.php
tests/Fixtures/openai/insufficient-quota-response-1.json
tests/Providers/OpenAI/OpenAIExceptionsTest.php

Handles OpenAI rate-limit errors (e.g. `insufficient_quota`) where no headers are set and the error is provided in the response.

feat(openai): set the name of unmatched OpenAI rate limit errors

---

src/Providers/OpenAI/Concerns/ValidatesResponse.php
tests/Providers/OpenAI/OpenAIExceptionsTest.php

This matches the `retryAfter` value of an OpenAI 429 rate limited response using the [same header as their Python library](https://github.com/openai/openai-python/blob/e36956673d9049713c91bca6ce7aebe58638f483/src/openai/_base_client.py#L621)

feat(openai): retry after header

---

docs/providers/anthropic.md
docs/providers/gemini.md
src/Providers/Gemini/Concerns/ExtractSearchGroundings.php
src/Providers/Gemini/Concerns/ValidatesResponse.php
src/Providers/Gemini/Handlers/Text.php
src/Providers/Gemini/Maps/SearchGroundingMap.php
src/Providers/Gemini/ValueObjects/MessagePartWithSearchGroundings.php
src/Providers/Gemini/ValueObjects/SearchGrounding.php
tests/Fixtures/gemini/generate-text-with-search-grounding-1.json
tests/Providers/Gemini/GeminiTextTest.php
tests/Providers/Gemini/ValueObjects/MessagePartWithSearchGroundingsTest.php
tests/Providers/Gemini/ValueObjects/SearchGroundingTest.php

This PR:
- allows you to enable [Google search grounding](https://ai.google.dev/gemini-api/docs/grounding?lang=rest) on text requests
- returns the data you need to build up footnotes and comply with Google's display requirements in `additionalContent`.
Gemini does not support:
- use of search grounding with other tools, without using the "Live" (websocket) API (so Prism will throw an exception if you try).
- search grounding for structured.

feat(gemini): text search grounding

---

docs/input-modalities/images.md

Added docs to add mime type to Image::fromUrl method when using urls which are not ending in the filetype e.g. temporary URLs

Docs Update images.md

---

src/Providers/Gemini/Handlers/Structured.php
src/Providers/Gemini/Handlers/Text.php
tests/Fixtures/FixtureResponse.php

This fixes a side issue highlighted in #269, caused by a regression in #219 that was stopped schemas from working. It also fixes another regression with Tools, but I believe unrelated to #269.
@sixlive I also noticed that `FixtureResponse` no longer took a wildcard route when recording. I assumed that was unintentionally so re-added but do shout if it was intentional.

bug(gemini): fix handler regressions

---

src/Providers/Gemini/Handlers/Embeddings.php

This PR fixes an issue with the JSON payload structure sent to the Gemini API.
The original payload was sending the `parts` field as an array containing an object:
```
'content' => [
'parts' => [
['text' => $request->inputs()],
],
],
```
However, the Gemini API expects parts to be a single object, not an array. This discrepancy resulted in the error:
Invalid JSON payload received. Unknown name "text" at 'content.parts[0]': Proto field is not repeating, cannot start list.
###Solution
The payload has been updated to send parts as a single object containing the text key:
```
'content' => [
'parts' => ['text' => $request->inputs()[0]],
],
```
This change ensures the request adheres to the expected API format, resolving the error.
Impact
- The API now receives a valid JSON payload.
- The …

bug(gemini): fix embedding structure input

---

docs/core-concepts/testing.md

Just a new example for testing embeddings as I needed it earlier in a project.
None.

docs: testing.md to add Embeddings

---

docs/providers/voyageai.md

Update documentation to reflect use of new method included in [v0.51.0](https://github.com/prism-php/prism/releases/tag/v0.51.0) to replace generate()

docs(readme): replace deprecated generate() method with asEmbeddings()

---

config/prism.php
docs/providers/deepseek.md
src/PrismManager.php
src/Providers/DeepSeek/DeepSeek.php

The deepseek API URL in the current project is fixed and official. Currently, there are many transfer platforms, such as openrouter, which also support it. So you need to change the deepseek API URL to a configurable file.

feat(deepseek): support api url configuration

---

src/Http/Controllers/PrismChatController.php

This PR simply adds `SystemMessage` to the mapping in `PrismChatController`.
I was using Open WebUI with a knowledge base, and the "RAG context" is added with `'role' => 'system'`.

feat(server): system messages

---

src/ValueObjects/Messages/UserMessage.php

Currently, [`SystemMessage`](https://github.com/prism-php/prism/blob/main/src/ValueObjects/Messages/SystemMessage.php), [`AssistantMessage`](https://github.com/prism-php/prism/blob/main/src/ValueObjects/Messages/AssistantMessage.php) both have a public property, `$content`.
I was writing a quick test script, and was trying to just log the output a list of all the messages. Surprisingly, it get's a little funky because of the [`UserMessage`](https://github.com/prism-php/prism/blob/main/src/ValueObjects/Messages/UserMessage.php#L22).
```
/** @var  $message Messages\SystemMessage|Messages\UserMessage|Messages\AssistantMessage|Messages\ToolResultMessage */
foreach ($response->messages as $message) {
if ($message instanceof Messages\SystemMessage) {
$this->info('System: '. $message->content); …
```

refactor: UserMessage public properties

---

docs/core-concepts/testing.md

Language specification on embedding testing was missing
none, docs

chore(docs): add missing language specification on embedding testing

---

src/Concerns/HasProviderMeta.php
src/Providers/Anthropic/Maps/MessageMap.php
src/Providers/Anthropic/Maps/ToolMap.php
src/Providers/DeepSeek/Maps/ToolMap.php
src/Providers/Gemini/Handlers/Text.php
src/Providers/OpenAI/Maps/ToolMap.php
tests/Concerns/HasProviderMetaTest.php
tests/Providers/Anthropic/AnthropicTextTest.php

I have been meaning to do this for a while, but in my head it was a bigger change than it actually was...!
`->providerMeta()` currently returns the full providerMeta for the specified provider (or an empty array) if the valuePath is not set. This is clunky and requires workarounds to handle null values.
This PR changes `->providerMeta()`  to:
- Return early if the valuePath is null (therefore not affecting behaviour if your intent is to grab the whole array).
- Return null if the valuePath is not set.
I've also been through and cleaned up where we have worked around this internally.
- `->providerMeta()` now returns null if the valuePath is not set, instead of returning the full providerMeta array for the provider. This _should_ only affect custom providers.

fix: providerMeta returns null if valuePath is not set

---

docs/.vitepress/config.mts

This is a tiny change but supper helpful. 
`VitePress` has this [local search](https://vitepress.dev/reference/default-theme-search#local-search) feature, which is in-browser index offline search. It's not that advanced but in our case it's more than enough.

feat(docs): add local search to documentation

---

docs/getting-started/configuration.md
src/Concerns/ConfiguresProviders.php
tests/Text/PendingRequestTest.php

Adds a providerConfig argument to `using()`, e.g.:
```php
Prism::text()
->using(Provider::OpenAI, 'gpt-4', [
'url' => 'new url'
]);
```
You can do this already with `usingProviderConfig()`, but this is slightly nicer DX and avoids re-resolving the provider.

feat: add providerConfig argument to using

---

src/Providers/OpenAI/Maps/ToolChoiceMap.php
tests/Providers/OpenAI/TextTest.php

Added mappings for ToolChoice::Any ('required') and ToolChoice::None ('none'). Keeps existing behavior for Auto, null, and invalid values.

Expand OpenAI tool choice mapping to support 'Any' and 'None' options

---

tests/Http/PrismChatControllerTest.php

The PrismChatController tests would fail sometimes due to timing, as the time was frozen after the responses were generated. Thus, they would usually work until a runner is too slow. To make sure they don't, it is now frozen at start of the test.
none

chore: freeze time for tests

---

src/Providers/Ollama/Handlers/Embeddings.php
src/Providers/Ollama/Handlers/Stream.php
src/Providers/Ollama/Handlers/Structured.php
src/Providers/Ollama/Handlers/Text.php

Whats up TJ!
Great work on this package. Finally got around to a new LLM project and decided to give it a go vs rolling my own. 
So far so good. 
I noticed Ollama options were missing, and added those with this PR.
Now users can do something like
```php
$response = Prism::text()
->usingTemperature(0.5)
->withMaxTokens(1000)
->withProviderOptions([
'stop' => ['<custom_stop_sequence>'],
])
```
To create a custom stop sequence. Other [options are available](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values).
The way it's implemented, `withProviderOptions` will take priority over any of the temperature, top_p, or token configurations, should the user manually define these in the `withProviderOptions`. This would be preferential, so users could use one …

refactor(ollama): enhance options handling in handlers

---

docs/core-concepts/testing.md
src/Testing/Concerns/CanGenerateFakeChunksFromTextResponses.php
src/Testing/PrismFake.php
tests/Testing/PrismFakeTest.php

I did play around with some approaches and now have a minimal surface area way to fake streaming text responses.
Originally, I thought about giving more control about the Chunks to be faked, but honestly I think there is not a lot of use to that. The way I chose now seems to me clean to use & easy to maintain. I just take a TextResponse and construct a stream of chunks from it:
```php
Prism::fake([
TextResponseFake::make()
->withText('fake response text'),
]);
$text = Prism::text()
->using('anthropic', 'claude-3-sonnet')
->withPrompt('What is the meaning of life?')
->asStream();
$outputText = '';
$toolCalls = [];
$toolResults = [];
foreach ($text as $chunk) {
$outputText .= $chunk->text;
}
expect($outputText)->toBe('fake response text');
```
If one wants to test tool calls, the steps need …

feat: fake streaming text responses

---

docs/providers/gemini.md
src/Providers/Gemini/Handlers/Stream.php
src/Providers/Gemini/Handlers/Structured.php
src/Providers/Gemini/Handlers/Text.php
src/Structured/ResponseBuilder.php
src/Text/ResponseBuilder.php
src/ValueObjects/Usage.php
tests/Fixtures/gemini/generate-text-with-a-prompt-with-no-thinking-budget-1.json
tests/Fixtures/gemini/generate-text-with-a-prompt-with-thinking-budget-1.json
tests/Providers/Gemini/GeminiTextTest.php

In the preview Gemini 2.5 models, Google introduced "thinking", and is enabled by default on these models. Without this feature, using the new models will always include thinking, which is billed at a higher rate and not always desirable. This PR enables you to configure a `thinkingBudget`, which Gemini views a max amount of tokens that may be used for thinking, or it can be set to 0 to disable it altogether.
This PR:
- Introduces a new `thoughtTokens` to the `Usage` class
- Leverages the `withProviderOptions()` method to inject a `thinkingBudget` when passed as a key, value pair
- Includes two tests that check for `thoughtTokens` in the `Usage` output
- Updates the documentation for Gemini to include this functionality
```
$response = Prism::text()
->using(Provider::Gemini, …
```

feat(gemini): Add support for Gemini 2.5 Thinking Budget

---

docs/.vitepress/config.mts
docs/package-lock.json
docs/package.json

Resolves #213 
This MR introduces LLM-friendly documentation files (llms.txt and llms-full.txt) for each page in the Prism docs. The goal is to make the documentation more accessible and usable for LLMs (Large Language Models) by providing structured, plain-text versions of the content. This change aligns with the original issue #213 and leverages the [vitepress-plugin-llms](https://github.com/okineadev/vitepress-plugin-llms) plugin to generate these files.

feat: add llm.txt and llms-full.txt support for docs

---

src/Providers/OpenAI/Handlers/Stream.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php

#377 (not yet tagged) introduced a regression with openai with the metadata property.
I don't think the array cast is necessary when wrapped with Arr::whereNotNull().
@sixlive this should be tagged along with 377 to avoid releasing the regression.

fix(openai): remove array cast from metadata

---

docs/providers/openai.md

Updating the docs to remove OpenAI limitation now that `ToolChoice::Any` is supported.

docs(openai): `ToolChoice::Any` now supported

---

src/Providers/Gemini/Handlers/Stream.php

The variable `$finishReason` is always `null` when using Gemini because it checks on a "done" value instead of using the appropriate function. This way is harder to determine when the chunks end
## Changes
Changed to use the `mapFinishReason` function when proecessing the stream
I tested using `gemini-2.0-flash`, so it may be different with the 2.5 version

Fixed Gemini stream finish reason always null

---

docs/providers/openai.md
src/Providers/OpenAI/Maps/MessageMap.php
src/ValueObjects/Messages/UserMessage.php
tests/Providers/OpenAI/MessageMapTest.php

Closes #358 
This PR introduces the concept of message additional parameters and implements them for the OpenAI message map

feat: user message additional attributes

---

src/Providers/Gemini/Handlers/Stream.php

Gemini stream handlers sends
```json
"generationConfig": {
"maxOutputTokens": 2048,
"thinkingConfig": []
}
```
While it should omit `thinkingConfig` if empty.
Related to #394 that fixed it for gemini structured handler, text handler it's working.
Fixes #419

fix(gemini): stream handler sends empty array for thinkingConfig

---

docs/core-concepts/streaming-output.md
src/Providers/Anthropic/Handlers/Stream.php
src/Providers/Anthropic/ValueObjects/StreamState.php
tests/Providers/Anthropic/StreamTest.php

Adds optional `Usage` to text Chunk and implements it for Anthropic.
In Anthropic there are some additional usage details, but we might implement them in a future improvement.
I had to change some things in Stream Handler because the stream was not being read entirely and finish reason was sent only at the end instead of sending all finish reasons.
This is currently generated chunks, no finish reason for tool calls, only last chunk has finish reason.
This is how it is with this PR
Closes #404

feat(anthropic): Add usage to stream chunk

---

docs/providers/anthropic.md
src/Providers/Anthropic/Handlers/Stream.php
src/Providers/Anthropic/Handlers/Text.php
src/Providers/Anthropic/Maps/MessageMap.php
src/ValueObjects/Messages/ToolResultMessage.php
tests/Providers/Anthropic/MessageMapTest.php

This PR adds support for caching tool results when using Anthropic's API. This feature reduces token usage and API costs when tool results are referenced multiple times within a conversation.
When using tools with Anthropic's Claude models, each tool result consumes input tokens every time it's referenced in subsequent API calls. For scenarios with multiple tool calls (e.g., checking weather in 5 cities), this can significantly increase costs and latency.
Added support for caching tool results using Anthropic's prompt caching feature. Tool results can now be cached for 5 minutes, reducing token usage on subsequent references.
1. Added HasProviderOptions trait to ToolResultMessage - Enables provider-specific configuration on tool result messages
2. Updated Anthropic's MessageMap - Adds …

feat(anthropic): tool result caching

---

docs/core-concepts/image-generation.md
src/Providers/OpenAI/Handlers/Images.php
src/ValueObjects/GeneratedImage.php
tests/Providers/OpenAI/ImagesTest.php

Adds base64 image support for `gpt-image-1` model

Add base64 support

---

src/Contracts/ProviderMediaMapper.php
src/Providers/Anthropic/Maps/DocumentMapper.php
src/Providers/Anthropic/Maps/ImageMapper.php

Anthropic wasn't calling validation on media mappers due to overwriting the constructor.
Not an issue that will have come up as Anthropic supports all current mediums. However, it came up extending the Anthropic mapper for the bedrock provider.

fix(anthropic): Anthropic media mappers call validation method

---

src/Embeddings/PendingRequest.php
src/Embeddings/Request.php
src/Images/PendingRequest.php
src/Images/Request.php
src/Structured/PendingRequest.php
src/Structured/Request.php
src/Text/PendingRequest.php
src/Text/Request.php
tests/Testing/AssertRequestTest.php

Closes #439
This PR adds the `providerKey` to the request object so that we can later assert it in our testing fixtures.

Add provider to request objects

---

docs/advanced/custom-providers.md

I took a look at the docs and saw the old version of the custom provider docs, before #434
So, I ran claude code with the style guide and instructions to align it with the new PR, only to find out it was already aligned, just not deployed.
I still like the style additions, examples, and the tips claude added so much that I decided to open this PR anyways.
none, docs

chore: add example to custom provider and apply style guide

---

src/Providers/DeepSeek/Handlers/Text.php
tests/Providers/DeepSeek/TextTest.php

When not sending tools an empty array is passed and this causes an error on DeepSeek side.
This PR removes `tools` parameter if empty.
DeepSeek [docs](https://api-docs.deepseek.com/api/create-chat-completion) shows `tools` parameter as nullable.
Fixes #465

fix(deepseek): text generation without tools

---

src/Providers/Anthropic/ValueObjects/StreamState.php
tests/Fixtures/anthropic/stream-basic-text-1.sse

Fixes setting usage in `StreamState` when there is a nested object like:
```json
"usage": {
"output_tokens": 104,
"server_tool_use": {"web_search_requests": 1}
}
```

fix(anthropic): nested usage

---

src/Providers/Ollama/Handlers/Embeddings.php
tests/Providers/Ollama/EmbeddingsTest.php

When provider options are not defined an empty array is passed and this causes an error on Ollama side.
This PR removes `options` parameter if empty.
Ollama [docs](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings) are not explicit but the example code shows `options` parameter as optional.
Fixes #460

fix(ollama): embeddings not working with empty options

---

src/Providers/OpenAI/Maps/ImageMapper.php
tests/Providers/OpenAI/TextTest.php

This MR add support for the detail for openai provider.
https://platform.openai.com/docs/guides/images-vision?api-mode=responses#specify-image-input-detail-level
Resolves #504
Usage:
```php
use Prism\Prism\Prism;
use Prism\Prism\ValueObjects\Media\Image;
$image = Image::fromLocalPath('/path/to/image.jpg')
->withProviderOptions(['detail' => 'high']);
$response = Prism::text()
->using('openai', 'gpt-4o')
->withPrompt('What do you see in this image?', [$image])
->asText();
```
No breaking Chnages.

feat(openai): add detail option to payload in ImageMapper

---

src/Providers/Anthropic/Anthropic.php
src/Providers/DeepSeek/DeepSeek.php
src/Providers/Gemini/Gemini.php
src/Providers/Groq/Groq.php
src/Providers/Mistral/Mistral.php
src/Providers/Ollama/Handlers/Stream.php
src/Providers/Ollama/Handlers/Structured.php
src/Providers/Ollama/Handlers/Text.php
src/Providers/Ollama/Ollama.php
src/Providers/OpenAI/OpenAI.php
src/Providers/OpenRouter/OpenRouter.php
src/Providers/VoyageAI/VoyageAI.php
src/Providers/XAI/XAI.php
tests/Providers/Ollama/StructuredTest.php
tests/Providers/Ollama/TextTest.php

Remove unsupported 'system' param from `api/chat` endpoint and allow multiple system prompts
Replace the incorrect use of the `system` body param with the correct `{ role, content }` message structure, as per Ollama's API spec. Now system prompts are prepended to the messages array to maintain compatibility with the chat format expected by `api/chat`. `system` body param is only available for `api/generate` endpoint. Since we are now prepending the system prompts, multiple system prompts are allowed by default, remove the restriction on multiple system prompts and remove the relevant tests as well.
N/A

fix(ollama-provider): remove unsupported 'system' param

---

src/Providers/OpenAI/Handlers/Audio.php
tests/Providers/OpenAI/AudioTest.php

Currently while using Openai Audio SpeechToText the correct usagae is not visible.
https://platform.openai.com/docs/api-reference/audio/createTranscription
No breaking change

fix(openai): update usage token keys to match API changes

---

docs/input-modalities/audio.md
docs/input-modalities/documents.md
docs/input-modalities/images.md
docs/input-modalities/video.md

The wrong parameter name is used in the docs.
In all `fromStoragePath` functions, change `disk` to `diskName` as used in the code.
Also remove any trailing whitespace at the ends of lines.
-

docs(media): update parameter names for fromStoragePath

---

docs/providers/openrouter.md
src/Providers/OpenRouter/Handlers/Stream.php
src/Providers/OpenRouter/Handlers/Structured.php
src/Providers/OpenRouter/Handlers/Text.php

This PR aims to improve the handling of OpenRouter `reasoning` parameter, as well as adhere to their suggested structure for structured responses.
For my use-case using a variety of newer models through OpenRouter, this was actually a fix rather than a breaking change, however it's possible that this may break things for older models.
Tested models include:
- OpenAI: gpt-oss-20b (free)
- Google: Gemma 3 12B
- Google: Gemini 2.0 Flash Lite
- OpenAI: GPT-5 Nano
- Google: Gemini 2.5 Flash Lite
- Google: Gemini 2.0 Flash
- Meta: Llama 4 Maverick
- Qwen: Qwen3 30B A3B Instruct 2507
- OpenAI: GPT-5 Mini
- MoonshotAI: Kimi K2
- Google: Gemini 2.5 Flash

feat(openrouter): Improve OpenRouter reasoning and structured response handling

---

docs/core-concepts/schemas.md
docs/core-concepts/structured-output.md
docs/core-concepts/testing.md
docs/providers/openrouter.md
docs/providers/xai.md

- Add provider-specific ObjectSchema requirement notes
- Clarify that ObjectSchema requirement is primarily for OpenAI strict mode
- Update core structured output and schemas documentation
- Modify provider docs (XAI, OpenRouter) to note OpenAI compatibility
- Remove incorrect universal requirement from Anthropic docs
- Update testing docs to clarify OpenAI-style structured output
Fixes #587

docs: Add ObjectSchema requirement warnings for structured output

---

src/ValueObjects/Media/Media.php
tests/ValueObjects/Media/MediaTest.php

When calling `->resource()` on an Url media, it recursively calls `->resource()` but always end up back in the same if-statement because the url check always takes precedence over the rawContent check.
```php
Media::fromUrl('https://prismphp.com/storage/diamond.png')->resource();
```
- Move the url check below the raw content check
- Fetch the url content, then continue the code so it will reach the rawContent check
Let me know if you prefer one of the alternative fixes over this one.

Prevent recursive endless loop on create a resource from url media
