.github/workflows/formatting.yml
.github/workflows/phpstan.yml
.github/workflows/tests.yml

Fix workflow targets so they run on PR

Fix workflow targets

---

src/Exceptions/PrismException.php
src/Tool.php
tests/ToolTest.php

Handle exception when invalid param passed to a tool

---

config/prism.php
src/Enums/Provider.php
src/PrismManager.php
src/Providers/Groq/Client.php
src/Providers/Groq/Groq.php
src/Providers/Groq/MessageMap.php
src/Providers/Groq/Tool.php
tests/Fixtures/groq/generate-text-with-a-prompt-1.json
tests/Fixtures/groq/generate-text-with-multiple-tools-1.json
tests/Fixtures/groq/generate-text-with-multiple-tools-2.json
tests/Fixtures/groq/generate-text-with-system-prompt-1.json
tests/Fixtures/groq/image-detection-1.json
tests/Fixtures/groq/text-image-from-base64-1.json
tests/Fixtures/groq/text-image-from-url-1.json
tests/Providers/GroqTextTest.php

This MR add support for [Groq](https://console.groq.com/docs/api-reference#chat-create).
Resolve #14 
CC @sixlive

Add Support For Groq

---

src/Concerns/NullableSchema.php
src/Schema/ArraySchema.php
src/Schema/BooleanSchema.php
src/Schema/EnumSchema.php
src/Schema/NumberSchema.php
src/Schema/ObjectSchema.php
src/Schema/StringSchema.php
tests/SchemaTest.php

Add nullable schema types

---

docs/providers/xai.md
src/Providers/XAI/Maps/MessageMap.php
tests/Fixtures/xai/image-detection-1.json
tests/Fixtures/xai/text-image-from-base64-1.json
tests/Fixtures/xai/text-image-from-url-1.json
tests/Providers/XAI/MessageMapTest.php
tests/Providers/XAI/XAITextTest.php

This MR add Support for XAI Image understanding https://docs.x.ai/docs/guides/image-understanding

xAI Image Understanding

---

docs/.vitepress/config.mts
docs/core-concepts/schemas.md
docs/core-concepts/structured-output.md
docs/core-concepts/tools-function-calling.md

Closes #81 
- Adds dedicated page for schemas
- Updates tools and structured output docs to point to the new page as a reference

Docs: Dedicated page for schemas

---

src/Providers/Ollama/Handlers/Embeddings.php

Fix Ollama embeddings exception prefix

---

src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php

OpenAI max_tokens to max_completion_tokens

---

docs/components/ProviderSupport.vue
src/Providers/Ollama/Handlers/Structured.php

Closes #127 
Support official Ollama JSON mode for structured outputs

Official Ollama JSON mode

---

src/Enums/StructuredMode.php
src/Providers/OpenAI/Support/StructuredModeResolver.php
tests/Providers/OpenAI/StructuredTest.php

Closes #124 
From everything that I can find o1 series models do not support structured output. This PR introduces an exception when trying to use these models with structured output.

Handle o1 Model Structured Output

---

src/Text/Generator.php
src/Text/Request.php

It looks like when I refactored I broke text generation with tools, this PR resolves things.

Fix text generation with tools

---

src/Text/Generator.php
src/Text/Response.php
src/Text/ResponseBuilder.php
tests/Http/PrismChatControllerTest.php
tests/Text/GeneratorTest.php

Adds text generation regression test for messages changes. The bug was introduced in the recent refactor #126

Text Generation Regression Test

---

config/prism.php
src/PrismManager.php
src/Providers/OpenAI/OpenAI.php
tests/Providers/OpenAI/TextTest.php

* added support for OpenAI Project Header (OpenAI-Project)
* (see https://platform.openai.com/docs/api-reference/authentication)

feat: OpenAI Project Header

---

composer.json
docs/getting-started/introduction.md
src/helpers.php
tests/HelpersTest.php

- Adds fluent helper `prism()`.
- Adds `src/helpers.php` with composer configuration.
- Adds test asserting instance resolved correctly.
- Adds blurb in documentation (wasn't 100% sure on where to put this one).

Adds prism fluent helper

---

docs/components/ProviderSupport.vue
docs/providers/gemini.md
src/Enums/ToolChoice.php
src/Providers/Gemini/Handlers/Text.php
src/Providers/Gemini/Maps/FinishReasonMap.php
src/Providers/Gemini/Maps/MessageMap.php
src/Providers/Gemini/Maps/ToolCallMap.php
src/Providers/Gemini/Maps/ToolChoiceMap.php
src/Providers/Gemini/Maps/ToolMap.php
tests/Fixtures/gemini/generate-text-with-multiple-tools-1.json
tests/Fixtures/gemini/generate-text-with-multiple-tools-2.json
tests/Fixtures/gemini/generate-text-with-required-tool-call-1.json
tests/Providers/Gemini/GeminiTest.php
tests/Providers/Gemini/MessageMapTest.php
tests/Providers/Gemini/ToolChoiceMapTest.php
tests/Providers/Gemini/ToolTest.php

Added Gemini Tool Call and Tool Choice Support.
API reference https://ai.google.dev/gemini-api/docs/function-calling#function_declarations

Add Gemini Tool Call Suport

---

docs/.vitepress/config.mts
docs/advanced/rate-limits.md
src/Concerns/ChecksSelf.php
src/Contracts/PrismRequest.php
src/Embeddings/Request.php
src/Exceptions/PrismRateLimitedException.php
src/Providers/Anthropic/Handlers/AnthropicHandlerAbstract.php
src/Providers/Anthropic/Handlers/Structured.php
src/Providers/Anthropic/Handlers/Text.php
src/Structured/Request.php
src/Text/Request.php
src/ValueObjects/ProviderRateLimit.php
src/ValueObjects/ResponseMeta.php
tests/Fixtures/FixtureResponse.php
tests/Providers/Anthropic/AnthropicRateLimitExceptionTest.php
tests/Providers/Anthropic/AnthropicTextTest.php
tests/Providers/Anthropic/StructuredTest.php

feat: rate limit exceptions and Anthropic implmentation

---

docs/advanced/error-handling.md
src/Exceptions/PrismException.php
src/Exceptions/PrismStructuredDecodingException.php
src/Structured/ResponseBuilder.php
tests/Structured/ResponseBuilderTest.php

Adds a new exception for structured decoding errors.

feat: add decoding exception

---

src/Contracts/Provider.php
src/Structured/Generator.php
src/Structured/PendingRequest.php
src/Text/Generator.php
src/Text/PendingRequest.php
tests/Structured/PendingRequestTest.php

This PR is in prep for provider migration as part of #185

refactor: update provider return types

---

src/Embeddings/Response.php

fix(embeddings): Update response doc block with float

---

src/Providers/Ollama/Handlers/Structured.php
src/Providers/OpenAI/Concerns/MapsFinishReason.php
src/Providers/OpenAI/Concerns/ValidatesResponses.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php
src/Providers/OpenAI/OpenAI.php

refactor(openai): Return Final Response

---

src/Providers/XAI/Concerns/MapsFinishReason.php
src/Providers/XAI/Concerns/ValidatesResponses.php
src/Providers/XAI/Handlers/Text.php
src/Providers/XAI/XAI.php
tests/Providers/XAI/XAITextTest.php

Based on https://github.com/echolabsdev/prism/issues/185 I have refactored XAI provider.
@sixlive can you please review and let me know if this is the correct one and I'll proceed with the all the other one which I have mentioned.

refactor(xai): return final Response

---

src/Providers/Mistral/Concerns/MapsFinishReason.php
src/Providers/Mistral/Concerns/ValidatesResponses.php
src/Providers/Mistral/Handlers/Text.php
src/Providers/Mistral/Maps/ToolMap.php
src/Providers/Mistral/Mistral.php

Based on https://github.com/echolabsdev/prism/issues/185 I have refactored  mistral provider.
@sixlive can you please review and let me know if this is the correct one and I'll proceed with the all the other one which I have mentioned.

refactor(mistral): Return FInal Response

---

src/Providers/DeepSeek/Concerns/MapsFinishReason.php
src/Providers/DeepSeek/Concerns/ValidatesResponses.php
src/Providers/DeepSeek/DeepSeek.php
src/Providers/DeepSeek/Handlers/Structured.php
src/Providers/DeepSeek/Handlers/Text.php
src/Text/PendingRequest.php
tests/Providers/DeepSeek/StructuredTest.php
tests/Providers/DeepSeek/TextTest.php

Based on #185 I have refactored deep-seek provider. 
@sixlive can you please review and let me know if this is the correct one and I'll proceed with the all the other one which I have mentioned.

refactor(deepseek): return final Response

---

docs/core-concepts/tools-function-calling.md

Adds a note to tools documentation explaining that you'll need to increase max steps in order to use tools.
Fixes #210

docs(tools): add max steps explanation

---

src/Providers/OpenAI/Handlers/Stream.php

fix(openai): Re-enable streaming option

---

src/Providers/Gemini/Maps/SchemaMap.php
tests/Fixtures/gemini/generate-structured-1.json
tests/Providers/Gemini/GeminiStructuredTest.php
tests/Providers/Gemini/SchemaMapTest.php

Fixes a bug where the type doesn't map correctly and adds tests.

bug(gemini): fix schema map and add tests

---

docs/core-concepts/testing.md

Update documentation to match #224 breaking changes.

Update doc testing.md to change ResponseMeta to Meta

---

src/Providers/Groq/Concerns/ValidateResponse.php
src/Providers/Groq/Handlers/Text.php
tests/Providers/Groq/GroqTextTest.php

Implements the rate limit exception and meta for Groq.
Note: I have not updated the docs page as I am doing a couple of these today and don't want to cause a conflict. Will circle back after PRs are merged to update.

feat(groq): rate limit exception and meta

---

docs/advanced/rate-limits.md
docs/providers/voyageai.md
src/Providers/OpenAI/Concerns/ProcessesRateLimits.php
src/Providers/OpenAI/Concerns/ValidatesResponse.php
src/Providers/OpenAI/Handlers/Embeddings.php
src/Providers/OpenAI/Handlers/Stream.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php
tests/Providers/OpenAI/EmbeddingsTest.php
tests/Providers/OpenAI/OpenAIExceptionsTest.php
tests/Providers/OpenAI/StreamTest.php

Implements rate limit handling for OpenAI embeddings and streaming.
Also updates the docs re: all of the recent rate limit additions.

feat(openai): embedding + streaming rate limits

---

docs/core-concepts/streaming-output.md

Fix stream docs by updating old syntax to the new one.

docs(stream): fix stream docs

---

docs/components/ProviderSupport.vue
src/Providers/Groq/Groq.php
src/Providers/Groq/Handlers/Structured.php
tests/Fixtures/groq/structured-1.json
tests/Providers/Groq/StructuredTest.php

This MR adds support for groq strutured output. 
https://console.groq.com/docs/api-reference#chat-create

feat: add groq structured support

---

README.md

Update README.md to fix the link to community contributors graph.
No breaking changes

docs: Fix link to community contributors on README

---

src/Providers/Mistral/Concerns/ValidatesResponse.php
src/Providers/Mistral/Handlers/Structured.php
src/Providers/Mistral/Handlers/Text.php

One approach for solving issue #282.

fix(mistral): error message handling

---

docs/providers/ollama.md

While working through the providers I found this code snippet. Thought I'd align it with the to not confuse beginners.

chore(docs): align code example with ollama provider

---

docs/input-modalities/documents.md

docs(readme) updated deprecated method.

docs: update generate with asText

---

docs/providers/openai.md
src/Concerns/ConfiguresStructuredOutput.php
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php
tests/Fixtures/openai/cache-usage-automatic-caching-1.json
tests/Fixtures/openai/cache-usage-automatic-caching-2.json
tests/Fixtures/openai/structured-cache-usage-automatic-caching-1.json
tests/Fixtures/openai/structured-cache-usage-automatic-caching-2.json
tests/Providers/OpenAI/StructuredTest.php
tests/Providers/OpenAI/TextTest.php

Fixes #316.
Note:
- I noticed whilst debugging that `usingStructuredMode()` was protected - which is presumably unintentional. I have therefore made it public.
- Automatic caching with OpenAI doesn't seem to work with JsonMode. I haven't dug into this in any detail - but the requests were identical - so this seems to be a limitation with OpenAI.
- OpenAI does not provide cache write detail - only read. I've therefore left write as null.

bug(openai): add cache usage for OpenAI

---

src/Providers/Gemini/Handlers/Text.php
tests/Providers/Gemini/GeminiTextTest.php

The file : [src/Providers/Gemini/Handlers/Text.php](https://github.com/prism-php/prism/edit/main/src/Providers/Gemini/Handlers/Text.php) : Contains an issue where the return value is not being retrieved correctly from the api response data.
Previously it was trying to access "message.content" whilst the api does not respond with `message`, instead it should be `candidates.0.content.parts.0.text`
Sample response:
```
{
"candidates": [
{
"content": {
"parts": [
{
"text": "Okay, I'm ready for a super test! Let me know what you'd like to test. I can do things like:
*   **Answer questions:** Ask me anything!
*   **Write code:** Specify the programming language and the task.
*   **Summarize text:** Give me text and I'll summarize it.
*   **Translate languages:** Tell me the source and target …
```

fix(Gemini): Gemini responses are empty strings instead of the actual response data

---

docs/.vitepress/config.mts
docs/core-concepts/provider-interoperability.md
src/Concerns/ConfiguresProviders.php
src/Concerns/HasPrompts.php
tests/Concerns/WhenProviderTest.php

This PR introduces `whenProvider` as a way to provide a path to easier provider interop.

feat: add whenProvider for provider interop

---

docs/components/ExceptionSupport.vue

Just noticed I missed this when I added wider support!

docs: update rate limit exception support

---

docs/components/ProviderSupport.vue
src/Providers/Mistral/Handlers/Stream.php
src/Providers/Mistral/Maps/FinishReasonMap.php
src/Providers/Mistral/Maps/MessageMap.php
src/Providers/Mistral/Maps/ToolChoiceMap.php
src/Providers/Mistral/Mistral.php
tests/Fixtures/mistral/stream-basic-text-1.sse
tests/Fixtures/mistral/stream-with-tools-1.sse
tests/Providers/Mistral/MessageMapTest.php
tests/Providers/Mistral/StreamTest.php

Add stream support for Mistral provider

feat(mistral): add stream support for Mistral provider

---

src/Providers/DeepSeek/Handlers/Structured.php

refactor(deepseek): new JSON mode message

---

src/Providers/Gemini/Maps/SchemaMap.php

fix(gemini): structured output with array schema

---

src/Providers/Ollama/Handlers/Embeddings.php

See https://github.com/prism-php/prism/issues/352

Fix Ollama Error when no options are provided.

---

src/Providers/Gemini/Maps/MessageMap.php

fix(gemini): MessageMap typo

---

docs/providers/anthropic.md

Removes an extra quote in the Anthropic docs

Remove extra quote

---

docs/.vitepress/config.mts
docs/core-concepts/image-generation.md
docs/providers/openai.md
src/Contracts/Provider.php
src/Images/PendingRequest.php
src/Images/Request.php
src/Images/Response.php
src/Images/ResponseBuilder.php
src/Prism.php
src/Providers/Anthropic/Anthropic.php
src/Providers/DeepSeek/DeepSeek.php
src/Providers/Gemini/Gemini.php
src/Providers/Groq/Groq.php
src/Providers/Mistral/Mistral.php
src/Providers/Ollama/Ollama.php
src/Providers/OpenAI/Handlers/Images.php
src/Providers/OpenAI/Maps/ImageRequestMap.php
src/Providers/OpenAI/OpenAI.php
src/Providers/VoyageAI/VoyageAI.php
src/Providers/XAI/XAI.php
src/Testing/ImageResponseFake.php
src/Testing/PrismFake.php
src/ValueObjects/GeneratedImage.php
tests/Providers/OpenAI/ImagesTest.php
tests/TestDoubles/TestProvider.php

This PR adds support for image generation for OpenAI and lays the ground work for additional image generation providers in the future.

feat: image generation

---

src/ValueObjects/ToolCall.php
tests/ValueObjects/ToolCallTest.php

fix: empty tool calls

---

composer.json

chore: testbench version

---

docs/providers/gemini.md

Re: #423 - adds caching docs for Gemini, which I missed when originally implemented.

docs(gemini): add caching docs

---

.gitignore

Does what it says on the tin! We may want to commit an "official" one eventually, but for now it'd be handy to ignore.

chore: add CLAUDE.md to gitignore

---

src/Providers/OpenAI/Concerns/BuildsTools.php
src/Providers/OpenAI/Handlers/Stream.php
src/Providers/OpenAI/Handlers/Text.php
tests/Fixtures/openai/stream-with-provider-tool-1.json
tests/Providers/OpenAI/StreamTest.php

Moved the buildTools logic into a new BuildsTools trait to avoid code duplication between the Stream and Text handlers. Updated both handlers to use the trait, and added a new test and fixture to verify provider tool support in streaming responses.
None

feat: add provider tools to oai stream handler

---

docs/components/ProviderSupport.vue

Update Docs
No Breaking CHnages

docs(groq): correct streaming support status to Supported

---

src/Providers/Anthropic/Anthropic.php
src/Providers/DeepSeek/DeepSeek.php
src/Providers/Gemini/Gemini.php
src/Providers/Groq/Groq.php
src/Providers/Mistral/Mistral.php
src/Providers/Ollama/Ollama.php
src/Providers/OpenAI/OpenAI.php
src/Providers/OpenRouter/OpenRouter.php
src/Providers/VoyageAI/VoyageAI.php
src/Providers/XAI/XAI.php

Last update php-cs-fixer changes keywords order setting visibility always first.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8823

style(pint): fix visibility required

---

src/Providers/OpenAI/Handlers/Structured.php
tests/Providers/OpenAI/StructuredTest.php

fix(openai): strict structured bug

---

src/Providers/DeepSeek/DeepSeek.php
src/Providers/DeepSeek/Handlers/Stream.php
src/Providers/DeepSeek/Handlers/Text.php
tests/Fixtures/deepseek/stream-basic-text-responses-1.json
tests/Fixtures/deepseek/stream-max-tokens-responses-1.json
tests/Fixtures/deepseek/stream-system-prompt-responses-1.json
tests/Fixtures/deepseek/stream-with-reasoning-responses-1.json
tests/Fixtures/deepseek/stream-with-tools-responses-1.json
tests/Fixtures/deepseek/stream-with-tools-responses-2.json
tests/Providers/DeepSeek/StreamTest.php

Add stream output for DeepSeek provider.

fixed(deepseek): add streaming output

---

src/Providers/OpenAI/Maps/DocumentMapper.php
src/Providers/OpenAI/OpenAI.php
tests/Fixtures/openai/text-response-with-document-1.json
tests/Providers/OpenAI/TextTest.php

fix(openai): document handling

---

docs/providers/openai.md
src/Providers/OpenAI/Handlers/Structured.php
src/Providers/OpenAI/Handlers/Text.php
src/Providers/OpenAI/Maps/FinishReasonMap.php
tests/Fixtures/openai/stream-reasoning-effort-1.json
tests/Fixtures/openai/structured-reasoning-effort-1.json
tests/Fixtures/openai/text-reasoning-effort-1.json
tests/Providers/OpenAI/StreamTest.php
tests/Providers/OpenAI/StructuredTest.php
tests/Providers/OpenAI/TextTest.php

refactor(openai): GPT-5 adjustments

---

src/Providers/OpenAI/Support/StructuredModeResolver.php

Adds support for GPT-5 structured mode.
Closes #572

feat(openai): gpt-5 structured support

---

src/Providers/Gemini/Handlers/Stream.php
src/Providers/Mistral/Handlers/Stream.php
tests/Providers/Gemini/GeminiStreamTest.php

fix(gemini): streaming output tool yields

---

src/Providers/Gemini/Maps/SchemaMap.php
src/Providers/Gemini/Maps/ToolMap.php
src/Providers/OpenAI/Handlers/Text.php
tests/Providers/ElevenLabs/AudioTest.php

Just a little typo fix. Thanks for your work on this!

Fix typo in exception message for max tokens
